// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbG9GnIQ4RXjLH8228CkE0yE7431oUBoI',
    appId: '1:655458570021:web:f13bf641b33dcf57f214cc',
    messagingSenderId: '655458570021',
    projectId: 'moto-sertao-24b07',
    authDomain: 'moto-sertao-24b07.firebaseapp.com',
    databaseURL: 'https://moto-sertao-24b07-default-rtdb.firebaseio.com',
    storageBucket: 'moto-sertao-24b07.appspot.com',
    measurementId: 'G-P0LM6BX49H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakS97nZTkL-0GEKcYky2LH4kGz68BZLs',
    appId: '1:655458570021:android:2558ca69e2e14bc1f214cc',
    messagingSenderId: '655458570021',
    projectId: 'moto-sertao-24b07',
    databaseURL: 'https://moto-sertao-24b07-default-rtdb.firebaseio.com',
    storageBucket: 'moto-sertao-24b07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBed9XJqtkX-7DUGFCXfEXRYY6nbXFk9iI',
    appId: '1:655458570021:ios:a6fb9678a84b6ca9f214cc',
    messagingSenderId: '655458570021',
    projectId: 'moto-sertao-24b07',
    databaseURL: 'https://moto-sertao-24b07-default-rtdb.firebaseio.com',
    storageBucket: 'moto-sertao-24b07.appspot.com',
    iosBundleId: 'com.MotoSertao.Drivers.motoSertaoFlutterDrivers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBed9XJqtkX-7DUGFCXfEXRYY6nbXFk9iI',
    appId: '1:655458570021:ios:99c660b2803c8ab9f214cc',
    messagingSenderId: '655458570021',
    projectId: 'moto-sertao-24b07',
    databaseURL: 'https://moto-sertao-24b07-default-rtdb.firebaseio.com',
    storageBucket: 'moto-sertao-24b07.appspot.com',
    iosBundleId: 'com.MotoSertao.Drivers.motoSertaoFlutterDrivers.RunnerTests',
  );
}
